#[derive(Debug, Clone)]
pub enum Action {
    FocusChange,
    ShowPlayerPicker(String, Option<String>),
    ShowPlaybackPicker(crate::providers::models::PlaybackSource),
    LaunchPlayer(crate::tui::state::PlayerKind, String, Option<String>),
    Tick,
    Key(crossterm::event::KeyEvent),
    MouseClick(u16, u16),
    Quit,
    GoBack,
    SelectLanguage(usize),
    Resize(u16, u16),
    ToggleHelp,
    ToggleTvMode,
    ToggleAddonMode,
    SwitchToStreamingMode,
    SwitchProvider(crate::providers::models::ProviderKind),
    ShowTvConfig,
    TvChannelsLoaded(Vec<crate::providers::tv::Channel>, usize),
    TvPlaylistAdd(String),
    TvPlaylistRemove(usize),
    TvReloadPlaylists,
    TvInputToggle(bool),
    ShowAddonManager,
    AddonAddManifest(String),
    AddonToggleEnabled(usize),
    AddonRemove(usize),
    AddonInputToggle(bool),
    Search {
        query: String,
        force_refresh: bool,
    },
    SelectSuggestion {
        query: String,
    },
    SearchSuccess {
        context: crate::providers::models::RequestContext,
        request_id: u64,
        query: String,
        page: usize,
        payload: serde_json::Value,
    },
    SearchFailure(crate::providers::models::RequestContext, u64, usize, String),
    FetchHomepage {
        tab_id: String,
        page: usize,
    },
    HomepageSuccess {
        request_id: u64,
        tab_id: String,
        page: usize,
        payload: serde_json::Value,
    },
    HomepageFailure(u64, String),
    Suggest(String),
    SuggestSuccess(u64, String, serde_json::Value),
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    Submit,
    TabPane,
    BackTabPane,
    FetchPreview(String),
    PreviewSuccess(u64, String, serde_json::Value),
    PreviewFailure(u64, String),
    PlayStream(bool),
    ShowSubtitlePopup(String, serde_json::Value, bool),
    ShowDownloadSubtitlePopup(serde_json::Value),
    ToggleThemePopup,
    SelectTheme(String),
    ShowBrowseMenu,
    SelectBrowse(crate::tui::state::BrowsePreset),
    SelectAddonCatalog(crate::providers::addons::models::AddonCatalogTarget),
    LaunchMpv(String, Option<String>),
    DownloadStream(Option<String>),
    StartDownload(Option<String>, Option<String>),
    UpdateDownload(Option<f64>, Option<String>),
    DownloadCompleted(String),
    DownloadFailed(String),
    DownloadPaused(String),
    ClearDownload,
    CancelDownload,
    PromptDownloadEpisode,
    ConfirmDownloadEpisode,
    PromptDownloadSeason,
    ConfirmDownloadSeason,
    ProcessDownloadQueue,
    FetchDetails(String, bool),
    DetailsSuccess(
        crate::providers::models::RequestContext,
        u64,
        String,
        serde_json::Value,
    ),
    DetailsFailure(crate::providers::models::RequestContext, u64, String),
    InitStreamPool(String),
    StreamPoolInitialized(String, Vec<u32>),
    FetchEpisodeStreams {
        subject_id: String,
        season: usize,
        episode: usize,
        force_refresh: bool,
    },
    EpisodeStreamsReady(
        crate::providers::models::RequestContext,
        u64,
        String,
        usize,
        usize,
        serde_json::Value,
    ),
    EpisodeStreamsFailed(
        crate::providers::models::RequestContext,
        u64,
        String,
        usize,
        usize,
        String,
    ),
    PosterSuccess(String, std::sync::Arc<image::DynamicImage>),
    SearchPosterLoaded(String, Option<std::sync::Arc<image::DynamicImage>>),
    UpdateAvailable(Result<Option<(String, String)>, String>),
    CheckForUpdates,
    StartSelfUpdate,
    SelfUpdateProgress(String),
    SelfUpdateComplete(Result<crate::updater::SelfUpdateOutcome, String>),
    SetStatus(String),
    Refresh,
    ClearCache,
    CacheCleared(Result<(), String>),
    LaunchPlayback(
        crate::tui::state::PlayerKind,
        crate::providers::models::PlaybackSource,
    ),
    MarkWatched(crate::history::WatchHistoryItem),
    UpdateProgress {
        item: crate::history::WatchHistoryItem,
        progress: u64,
        duration: Option<u64>,
        completed: bool,
    },
    ReconcileHistory,
    PlayerCrashed(Option<i32>, String),
    PlayerExited,
    Notify(crate::models::NotificationKind, String, String),
}
